### ISSUE TITLE
When adding a new service, flipping from one service type back to none causes error

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-status-pages#109] opened 2020-08-26 01:52 UTC
## Steps to Reproduce

- Add a new service
- Choose a type like RSS
- Flip back to none
- Experience an unrecoverable error

## Expected Behaviour

- Handle the error gracefully or avoid it all together

**Comment by aso1124** [comment] 2023-01-13 17:42
Closing - unable to reproduce.

**Closed by aso1124** 2023-01-13 17:42 UTC
Labels: bug
